spring:
  mustache:
    # ??? ??? ???? .mustache? ???? Mustache
    # ??? ??? ????? ??
    suffix: .mustache
    # ??? ??? ???
    # ?? ??? src/main/resources/templates/? ??
    prefix: classpath:/templates/
    # ?? ? ??? ??? ?????? ??
    # ?? ? ?? ????? ? (??????? true? ?? ??)
    cache: false
    # ??? ??? UTF-8 ????? ???? ?? ? ??? ?? ??
    charset: UTF-8

server:
  # ??????? ??? ??? 8080?? ?? (???? 8080, ?? ? ?? ??)
  port: 8080

logging:
  level:
    # Spring Web ?? ??? DEBUG ????
    # ???? ??/?? ?? ??? ?? ? ?? ??
    org.springframework.web: DEBUG